#!/usr/bin/env python3
"""Stamp a content version onto the CSS links and the JS module graph.

GitHub Pages serves these files with a ten-minute max-age, so without a version
in the URL a returning visitor can get new JS against an old stylesheet. A page
with half its rules missing looks broken rather than stale.

CSS is easy: add ?v=HASH to each <link>. JS is harder without a bundler, because
the modules import each other by relative path, so a version on the entry point
alone leaves the children cached. An import map fixes that with no build step:
every module URL is remapped to its versioned form, and relative import
specifiers resolve through it.

The map is regenerated from the filesystem on every run, so it cannot drift out
of step with the files. Idempotent: run it as often as you like.
"""
from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DOCS = REPO / "docs"
PAGES = ("index.html", "selftest.html")
BEGIN = "<!-- BEGIN generated by tools/11_stamp_assets.py -->"
END = "<!-- END generated by tools/11_stamp_assets.py -->"


def assets() -> tuple[list[Path], list[Path]]:
    css = sorted(DOCS.glob("css/*.css"))
    js = sorted(DOCS.glob("js/**/*.js"))
    return css, js


def version(paths: list[Path]) -> str:
    h = hashlib.sha256()
    for p in paths:
        h.update(str(p.relative_to(DOCS)).encode())
        h.update(p.read_bytes())
    return h.hexdigest()[:10]


def strip_query(url: str) -> str:
    return url.split("?", 1)[0]


def main() -> int:
    check_only = "--check" in sys.argv
    css, js = assets()
    if not css or not js:
        print("[11] FATAL: no css/ or js/ files found under docs/", file=sys.stderr)
        return 1
    v = version(css + js)

    # Relative keys so the map works under https://user.github.io/<repo>/ as well
    # as at a domain root: they resolve against the document base URL.
    imports = {f"./{p.relative_to(DOCS).as_posix()}": f"./{p.relative_to(DOCS).as_posix()}?v={v}"
               for p in js}
    block = (BEGIN + "\n<script type=\"importmap\">\n"
             + json.dumps({"imports": imports}, indent=1)
             + "\n</script>\n" + END)

    for name in PAGES:
        path = DOCS / name
        src = path.read_text()

        # 1. version every stylesheet link
        def css_link(m: re.Match) -> str:
            return f'{m.group(1)}{strip_query(m.group(2))}?v={v}{m.group(3)}'
        src = re.sub(r'(<link[^>]*href=")([^"]+\.css(?:\?[^"]*)?)(")', css_link, src)

        # 2. version the module entry point
        src = re.sub(r'(<script[^>]*type="module"[^>]*src=")([^"]+\.js(?:\?[^"]*)?)(")',
                     lambda m: f'{m.group(1)}{strip_query(m.group(2))}?v={v}{m.group(3)}', src)

        # 3. replace or insert the import map, before any module script
        if BEGIN in src:
            src = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: block, src, flags=re.S)
        else:
            src = src.replace("</head>", block + "\n</head>", 1)

        if src == path.read_text():
            print(f"[11] {name}: already at v={v}")
            continue
        if check_only:
            print(f"[11] {name} is out of date: run tools/11_stamp_assets.py", file=sys.stderr)
            return 1
        path.write_text(src)
        print(f"[11] {name}: stamped v={v}")

    print(f"[11] {len(css)} stylesheet(s), {len(js)} module(s) in the import map")
    return 0


if __name__ == "__main__":
    sys.exit(main())
